// Generates supabase/seed.sql directly from the current mock data
// (src/lib/data/categories.ts, products.ts) so the seed is always
// byte-for-byte consistent with what's on the site — no hand-transcribed
// SQL to drift out of sync.
//
// Run with: npx tsx scripts/generate-seed-sql.ts

import { writeFileSync } from "node:fs";
import { categories } from "../src/lib/data/categories";
import { products } from "../src/lib/data/products";

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  return `ARRAY[${values.map(sqlString).join(", ")}]`;
}

function sqlJsonb(value: unknown): string {
  const json = JSON.stringify(value);
  return `${sqlString(json)}::jsonb`;
}

const lines: string[] = [];
lines.push("-- Samprada Gifts — seed data");
lines.push("-- Auto-generated by scripts/generate-seed-sql.ts — do not hand-edit.");
lines.push("-- Run schema.sql first, then this file, in Supabase SQL Editor.");
lines.push("");
lines.push("truncate table reviews, products, categories cascade;");
lines.push("");

lines.push("-- Categories");
lines.push("insert into categories (id, slug, name, description, image_url, product_count) values");
lines.push(
  categories
    .map(
      (c, i) =>
        `  (${sqlString(c.id)}, ${sqlString(c.slug)}, ${sqlString(c.name)}, ${sqlString(c.description)}, ${sqlString(c.image)}, ${c.productCount})${i === categories.length - 1 ? ";" : ","}`
    )
    .join("\n")
);
lines.push("");

lines.push("-- Products");
lines.push(
  "insert into products (id, slug, name, tagline, category_slug, price, mrp, rating, review_count, images, badges, min_qty, description, highlights, specifications, packaging, shipping, budget_tier) values"
);
lines.push(
  products
    .map((p, i) => {
      const row = [
        sqlString(p.id),
        sqlString(p.slug),
        sqlString(p.name),
        sqlString(p.tagline),
        sqlString(p.categorySlug),
        String(p.price),
        String(p.mrp),
        String(p.rating.toFixed(1)),
        String(p.reviewCount),
        sqlTextArray(p.images),
        sqlTextArray(p.badges ?? []),
        String(p.minQty ?? 1),
        sqlString(p.description),
        sqlTextArray(p.highlights),
        sqlJsonb(p.specifications),
        sqlTextArray(p.packaging),
        sqlTextArray(p.shipping),
        p.budgetTier ? sqlString(p.budgetTier) : "null",
      ].join(", ");
      return `  (${row})${i === products.length - 1 ? ";" : ","}`;
    })
    .join("\n")
);
lines.push("");

const allReviews = products.flatMap((p) => p.reviews.map((r) => ({ ...r, productSlug: p.slug })));
lines.push("-- Reviews");
lines.push("insert into reviews (id, product_slug, author, rating, review_date, title, body, verified) values");
lines.push(
  allReviews
    .map((r, i) => {
      const row = [
        sqlString(r.id),
        sqlString(r.productSlug),
        sqlString(r.author),
        String(r.rating),
        sqlString(r.date),
        sqlString(r.title),
        sqlString(r.body),
        String(!!r.verified),
      ].join(", ");
      return `  (${row})${i === allReviews.length - 1 ? ";" : ","}`;
    })
    .join("\n")
);
lines.push("");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log(`Wrote supabase/seed.sql — ${categories.length} categories, ${products.length} products, ${allReviews.length} reviews.`);
